Suppress deprecated notice on PHP8.1
BenSampo/laravel-enum pull request #236
Opened 2021-11-21 21:20 UTC by pyrou

**Related Issue/Intent**

Resolves #235 

**Changes**

Fix following notice
> Return type of BenSampo\Enum\Enum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Breaking changes**

Code is backward compatible for all currently supported php versions (^7.3|^8.0)

2021-11-21 21:21 UTC, atymic commented
This method never returns a string so it's going to cause type errors.

2021-11-21 23:52 UTC, pyrou commented
This method was documented as returning a string, it is calling ˋtoArray()ˋ that in its turn is documented to return a string.

In the end, it returns $value documented to hold a mixed value. So you are right, this can lead to a type error.

I'll change return type to `mixed` (including all related PHPdoc)

2021-12-08 21:36 UTC, pyrou commented
Ping @BenSampo

2022-01-11 08:55 UTC, spawnia requested changes

2022-01-11 08:55 UTC, spawnia commented on src/Enum.php
> +    public function jsonSerialize(): mixed
```suggestion
    public function jsonSerialize()
```

`mixed` is only available from PHP 8.0 forward.

2022-01-22 14:50 UTC, eduardoturconi commented
ping @BenSampo

2022-01-23 13:57 UTC, nitrogenium commented
ping @BenSampo

2022-01-31 19:43 UTC, merged