Fix issues #259
BenSampo/laravel-enum pull request #260
Opened 2022-03-24 16:04 UTC by trippo

Resolves #259

2022-05-24 03:20 UTC, suleymanozev commented
@BenSampo Please review. This issue is causing an error in Nova.

2022-11-11 18:09 UTC, daniouyea commented
@BenSampo Please review. This issue is causing an error in Nova.

2022-11-26 10:43 UTC, trippo commented
@daniouyea and @suleymanozev i created a package to replace this called [laravel-enum-helper](https://github.com/datomatic/laravel-enum-helper) and  related [laravel-enum-collections](https://github.com/datomatic/laravel-enum-collections) and [nova-enum-field](https://github.com/datomatic/nova-enum-field)

2022-12-07 09:52 UTC, spawnia commented
I believe this PR would break the existing translations entirely, so it is not something we can merge and release in the current major version.

2023-03-14 10:35 UTC, spawnia commented
I don't understand entirely what changes would be necessary for users of this library to adapt to this change. Can you describe in `UPGRADE.md`?

2023-03-14 10:39 UTC, spawnia requested changes

2023-03-14 10:39 UTC, spawnia commented on README.md
> +#### Be carefull
```suggestion
#### Validation messages
```

2023-03-14 10:39 UTC, spawnia commented on README.md
> +If you want to have validation messages, you must declares them on resources/lang/[locale]/validation.php
How would the app behave if no such messages were defined?

2023-03-14 10:39 UTC, spawnia commented on composer.json
> +        "illuminate/contracts": "^9.0|^10.0",
Laravel 10 support was added in https://github.com/BenSampo/laravel-enum/commit/0d1b8abc32a75dc378fe912c5bf7b2d77323f8fb, you would just need to update your branch with the latest changes in `master`.

2023-05-08 08:46 UTC, spawnia commented
Closing due to lack of response.

2023-05-08 08:46 UTC, closed without merging